## Condizionamento del problema della soluzione di un sistema lineare

In [39]:
import numpy as np
import scipy as sp

# Esercizio 1
- Costruire la matrice di Vandermonde A, generata dal vettore x=[1.0,2.0,...,6.0] utilizzando la funzione np.vander(x, increasing=True) di numpy. 
- Calcolarne l'indice di condizionamento in norma infinito senza utilizzare la funzione cond di numpy.linalg e poi confrontarne il valore con quello ottenuto utilizzando la funzione.
- Considerare il sistema lineare Ax=b  con matrice dei coefficienti A e termine noto costruito in maniera tale che la soluzione esatta sia il vettore x=[1,1,1,1,1,1] (ogni sua componente è 1) e risolverlo usando il metodo solve del modulo linalg di Scipy.
- perturbare il vettore dei termini noti della quantità
- 
$$
\delta b = 0.025 \, \ast \,
\left [
\begin{array}{c}
1\\
0\\
0\\
0
\end{array}
\right ]
$$
- Risolvere il sistema con termine noto pertubato $b + \delta b$ ((usando il metodo solve del modulo linalg di Scipy).
- Calcolare l'errore relativo sul termine noto e l'errore relativo sulla soluzione. Cosa si può concludere?

N.B. per il calcolo dell'inversa della matrice di A usare la funzione di numpy.linalg.inv(A).


In [45]:
def infty_norm(A):
    return np.max(np.sum(np.abs(A), axis=1))
# Così, perchè sono disperato e non ricordo un cazzo
def norm_1(A):
    return np.max(np.sum(np.abs(A), axis=0))
def norm_2(A):
    return np.max(np.linalg.eigvals(A @ A.T))
x = np.linspace(start=1.0, stop=6.0, num=6)
A = np.vander(x, increasing=True)
print("Matrice di Vandermonde:\n", A)
my_condizionamento = infty_norm(A) * infty_norm(np.linalg.inv(A))
print("condizionamento calcolato: {:e}".format(my_condizionamento))
numpy_condizionamento = np.linalg.cond(A, np.inf)
print("condizionamento calcolato da numpy: {:e}".format(numpy_condizionamento))

# costruzione termine noto 'b'
b = np.sum(A, axis=1).reshape((6,1)) 
b_pert = b.copy()
b_pert[0] += 0.025

# soluzione esa
x_correct = sp.linalg.solve(A, b)
x_pert = sp.linalg.solve(A, b_pert)
errore_sol = np.linalg.norm(x_pert - x_correct, ord=np.inf) / np.linalg.norm(x_correct, ord=np.inf)

print("Sistema risolto senza perturbazioni: ", x_correct)
print("Sistema risolto con perturbazioni: ", x_pert)
print("Errore nella soluzione: ", errore_sol)

Matrice di Vandermonde:
 [[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01 2.430e+02]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02 1.024e+03]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02 3.125e+03]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03 7.776e+03]]
condizionamento calcolato: 1.204321e+06
condizionamento calcolato da numpy: 1.204321e+06
Sistema risolto senza perturbazioni:  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Sistema risolto con perturbazioni:  [[1.15      ]
 [0.7825    ]
 [1.12083333]
 [0.96770833]
 [1.00416667]
 [0.99979167]]
Errore nella soluzione:  0.2174999999902107


## Esercizio 2
Assegnato il sistema lineare $Ax = b$, con
$$
A =
\left [
\begin{array}{ccc}
6 & 63 & 662.2\\
63 & 662.2 & 6967.8\\
662.2 & 6967.8 & 73393.5664
\end{array}
\right ], \qquad
b =
\left [
\begin{array}{c}
1.1\\
2.33\\
1.7
\end{array}
\right ]
$$
- trovare il vettore soluzione $x$ (usando il metodo solve del modulo linalg di Scipy);
- perturbare la matrice dei coefficienti della quantità
$$
\delta A =
0.01 \, \ast \,
\left [ \begin{array}{ccc}
1 & 0 & 0\\
0 & 0 & 0\\
0 & 0 & 0
\end{array}
\right ]
$$
quindi calcolare l'errore relativo sulla soluzione e confrontarlo con la
perturbazione relativa sui dati di ingresso. Cosa si osserva?

In [55]:
# Matrice estremamente mal condizionata
A = np.array([
    [6, 63, 662.2],
    [63, 662.2, 6967.8],
    [662.2, 6967.8, 73393.5664]
])
b = np.array([1.1, 2.33, 1.7])
x_correct = sp.linalg.solve(A, b)

A_pert = A.copy()
A_pert[0][0] += 0.01
x_pert = sp.linalg.solve(A_pert, b)

condizionamento_A = np.linalg.cond(A, np.inf)
print("Condizionamento matrice A: {:e}".format(condizionamento_A))

errore_dati = np.linalg.norm(A_pert - A, np.inf) / np.linalg.norm(A, np.inf)
print("Errore sui dati: {:e}".format(errore_dati))

errore_sol = np.linalg.norm(x_pert - x_correct, np.inf) / np.linalg.norm(x_correct, np.inf)
print("Errore sulla soluzione: {:e}".format(errore_sol))

Condizionamento matrice A: 1.975302e+10
Errore sui dati: 1.234209e-07
Errore sulla soluzione: 9.995082e-01


## Esercizio 3
 
Assegnato il sistema lineare $Ax = b$, con $A$ matrice di Hilbert di ordine
$4$ e $b = [1, 1, 1, 1]^T$,
 - trovare il vettore soluzione $x$ (usando il metodo solve del modulo linalg di Scipy);
 -  perturbare il vettore dei termini noti della quantità
$$
\delta b = 0.01 \, \ast \,
\left [
\begin{array}{c}
1\\
-1\\
1\\
-1
\end{array}
\right ]
$$
quindi calcolare la soluzione del sistema $A x_p= b_p$ con termine noto $b_p=b+ \delta b$.
Calcolare l'errore relativo sulla soluzione e confrontarlo con la perturbazione relativa sui dati di ingresso. Cosa si osserva?

Nota: per la costruzione della matrice di Hilbert usare la funzione hilbert(n) del modulo scipy.linalg
(scipy.linalg.hilbert(n))  dove bisogna specificare l'ordine n della matrice.

In [74]:
n = 4
A = sp.linalg.hilbert(n)
b = np.ones(n)
# Particolarmente malcondizionata
cond = np.linalg.cond(A, np.inf)
print("Condizionamento matrice di Hilbert di ordine {}: {:e}".format(n, cond))
b_pert = b.copy()
b_pert += np.array([.01,-.01,.01,-.01])

x_corr = sp.linalg.solve(A, b)
x_pert = sp.linalg.solve(A, b_pert)

errore_dati = np.linalg.norm(b_pert - b) / np.linalg.norm(b)
errore_sol = np.linalg.norm(x_pert - x_corr) / np.linalg.norm(x_corr)
print(errore_dati, errore_sol)

# errore dati del 1% --> errore soluzione del 73%!

Condizionamento matrice di Hilbert di ordine 4: 2.837500e+04
0.010000000000000009 0.7296001237811043


## Metodi diretti per la soluzione numerica di un sistema lineare

## Nota 1.
La funzione *scipy.linalg.lu(A)*  , presa in input una matrice A a rango massimo, restituisce in output le matrici $P^T$,L,U,  della fattorizzazione di LU della matrice A in maniera tale che PA=LU (restituisce la matrice di permutazione trasposta)

In [2]:
import numpy as np
import scipy as sp
from scipy.linalg import lu
A=np.array([[2,1],[3,4]])
PT,L,U=lu(A)  #Restituisce in output la trasposta della matrice di Permutazione
P=PT.copy()   #P è la matrice di permutazione
print("A=",A)
print("L=",L)
print("U=",U)
print("P=",P)
#LU è la fattorizzazione di P*A (terorema 2)
A1=P@A # equivale al prodotto matrice x matrice np.dot(P,A)
A1Fatt=L@U # equivale a np.dot(L,U)
print("Matrice P*A \n", A1)
print("Matrice ottenuta moltipicando Le ed U \n",A1Fatt)


A= [[2 1]
 [3 4]]
L= [[1.         0.        ]
 [0.66666667 1.        ]]
U= [[ 3.          4.        ]
 [ 0.         -1.66666667]]
P= [[0. 1.]
 [1. 0.]]
Matrice P*A 
 [[3. 4.]
 [2. 1.]]
Matrice ottenuta moltipicando Le ed U 
 [[3. 4.]
 [2. 1.]]


## Nota 2
La funzione *scipy.linalg.cholesky(a, lower=True)*, presa in input una matrice simmetrica e definta positiva restituisce in output la matrice L triangolare inferiore tale che $A=L \cdot L^T$. Se la matrice in input non è definita positiva, restituisce un errore.

In [3]:
from scipy.linalg import cholesky
A=np.array([[2,1,3],[1,5,7],[3,7,12]])
print(A)

[[ 2  1  3]
 [ 1  5  7]
 [ 3  7 12]]


In [4]:
L=cholesky(A,lower=True)
print(L)
A1=L@L.T
print("A1=\n",A1)

[[1.41421356 0.         0.        ]
 [0.70710678 2.12132034 0.        ]
 [2.12132034 2.59272486 0.8819171 ]]
A1=
 [[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Nota 3
La funzione *scipy.linalg.qr(a)*, presa in input una matrice A (nxn)  a rango massimo, restituisce in output le matrici Q (ortogonale di dimensione nxn) ed una matrice R (nxn) triangolare superiore tale che $A=Q \cdot R$

In [5]:
from scipy.linalg import qr
A=np.array([[2,1,3],[1,5,7],[3,7,12]])
Q,R=qr(A)
print("Q=",Q)
print("R=",R)
A1=Q@R
print(A1)

Q= [[-0.53452248  0.6882472  -0.49051147]
 [-0.26726124 -0.6882472  -0.67445327]
 [-0.80178373 -0.22941573  0.55182541]]
R= [[ -3.74165739  -7.48331477 -13.09580085]
 [  0.          -4.35889894  -5.50597761]
 [  0.           0.           0.42919754]]
[[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Esercizio 4
- si implementi una function LUsolve(P,A,L,U,b) che risolve il sistema lineare Ax=b nel caso di fattorizzazione $PA = LU$ assegnata,
combinando i metodi di risoluzione in avanti ed all'indietro  implementati nel file SolveTriangular.py.
- si testi sulla matrice A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]]) con termine noto b scelto in maniera tale che la soluzione esatta del sistema lineare sia il vettore formato da tutti 1.

In [83]:
from SolveTriangular import Lsolve, Usolve

def LUsolve(P, A, L, U, b):
    Pb = P @ b
    y, ok = Lsolve(L, Pb)
    if ok == 0:
        return Usolve(U, y)
    return None, None

A = np.array([
    [2, 5, 8, 7], 
    [5, 2, 2, 8], 
    [7, 5, 6, 6], 
    [5, 4, 4, 8]
])
b = np.sum(A, axis=1).reshape((4,1)) # Sommo gli elementi riga per riga
print(f"A={A}")
print(f"b={b}")
Pt, L, U = sp.linalg.lu(A)
print(f"x={LUsolve(Pt.T, A, L, U, b)[0]}")

A=[[2 5 8 7]
 [5 2 2 8]
 [7 5 6 6]
 [5 4 4 8]]
b=[[22]
 [17]
 [24]
 [21]]
x=[[1.]
 [1.]
 [1.]
 [1.]]


## Esercizio 5
Si implementi una function *solve_nsis(A,B)* per il calcolo della soluzione di un generale sistema lineare $AX = B$, con $X, B$ matrici, che usi la fattorizzazione LU della matrice PA, per risolvere n sistemi lineari: aventi la stessa matrice dei coefficienti A e termine noto l'i-esima colonna della matrice B. 
Utilizzarla poi per il calcolo dell'inversa delle
matrici non singolari
$$
A=\left[
\begin{array}{ccc}
3 & 5 & 7\\
2 & 3 & 4\\
5 & 9 & 11
\end{array}
\right ], \qquad
A=\left[
\begin{array}{cccc}
1 & 2 & 3 & 4\\
2 & -4 & 6 & 8\\
-1 & -2 & -3 & -1\\
5 & 7 & 0 & 1
\end{array}
\right ],
$$
confrontando i risultati ottenuti con l'output
della funzione  *scipy.linalg.inv(A)*

In [135]:
def solve_nsis(A, B):
    m, n = A.shape # 'm' righe, 'n' colonne
    if n != m:
        print("Matrice non quadrata!")
        return None
    Pt, L, U = sp.linalg.lu(A)
    P = Pt.T
    X = np.zeros((n, n))
    for col in range(B.shape[1]):
        b = B[:,col]
        X[:,col] = LUsolve(P, A, L, U, b)[0].reshape((n,))
    return X

A1 = np.array([
    [3, 5, 7],
    [2, 3, 4],
    [5, 9, 11]
])

A2 = np.array([
    [1, 2, 3, 4],    
    [2, -4, 6, 8],    
    [-1, -2, -3, -1],    
    [5, 7, 0, 1],    
])

cond_A1 = np.linalg.cond(A1, np.inf)
cond_A2 = np.linalg.cond(A2, np.inf)

# per calcolare le inverse di A1 e A2, scelgo B come matrice identità
B1 = np.eye(A1.shape[0])
B2 = np.eye(A2.shape[0])

my_inv_A1 = solve_nsis(A1, B1)
my_inv_A2 = solve_nsis(A2, B2)
print(f"my-A1-inv=\n{my_inv_A1}")
print(f"my-A2-inv=\n{my_inv_A2}")

print()
A1_inv = np.linalg.inv(A1)
A2_inv = np.linalg.inv(A2)
print(f"A1_inv=\n{A1_inv}")
print(f"A2_inv=\n{A2_inv}")

err_sol_A1 = np.linalg.norm(my_inv_A1 - A1_inv, np.inf) / np.linalg.norm(A1_inv, np.inf)
err_sol_A2 = np.linalg.norm(my_inv_A2 - A2_inv, np.inf) / np.linalg.norm(A2_inv, np.inf)

print()
print(f"Errore sulla soluzione 1: {err_sol_A1:e}")
print(f"Errore sulla soluzione 2: {err_sol_A2:e}")

my-A1-inv=
[[-1.5  4.  -0.5]
 [-1.  -1.   1. ]
 [ 1.5 -1.  -0.5]]
my-A2-inv=
[[-4.16666667e-01  1.75000000e-01 -6.66666667e-02  2.00000000e-01]
 [ 2.50000000e-01 -1.25000000e-01  4.13612499e-17 -8.16340459e-18]
 [-1.38888889e-01  2.50000000e-02 -4.22222222e-01 -6.66666667e-02]
 [ 3.33333333e-01  3.26536184e-18  3.33333333e-01 -8.70763157e-18]]

A1_inv=
[[-1.5  4.  -0.5]
 [-1.  -1.   1. ]
 [ 1.5 -1.  -0.5]]
A2_inv=
[[-4.16666667e-01  1.75000000e-01 -6.66666667e-02  2.00000000e-01]
 [ 2.50000000e-01 -1.25000000e-01 -0.00000000e+00 -8.16340459e-18]
 [-1.38888889e-01  2.50000000e-02 -4.22222222e-01 -6.66666667e-02]
 [ 3.33333333e-01  4.62592927e-18  3.33333333e-01 -9.25185854e-18]]

Errore sulla soluzione 1: 1.480297e-16
Errore sulla soluzione 2: 1.455147e-16


## Esercizio 6
Sfruttando la fattorizzazione PA=LU  di una delle matrici del punto precedente, calcolarne il determinante.


## Esercizio 7
Per valori di $n = 4 : 6 : 40$, si consideri il sistema lineare $A_n x = b$ con
$A_n$ matrice di Hankel di ordine $n$ di elementi
$$
a^{(n)}_{i,n+k-i}
=
\left \{
\begin{array}{ll}
2^k & \hbox{se} \ k > 0,\\
2^{1/(2-k)} & \hbox{se} \ k \leq 0,
\end{array}
\right .
\qquad
i = 1, ..., n, \ \  k = i + 1-n, ..., i,
$$
e $b$ scelto in modo che risulti $x = [1, 1, ..., 1]^T$. Si risolva tale sistema
con il metodo di fattorizzazione LU della matrice PA
e il metodo di fattorizzazione QR (Q,R  =scipy.linalg.qr(A)).
Calcolare gli errori relativi $\| \delta x \|_2/\|x\|_2$ da cui sono affette
le soluzioni calcolate con i due metodi e produrre, al variare di $n$, un
grafico in scala logaritmica ( matplotlib.plyplot.loglog) degli errori relativi calcolati. Che cosa si
osserva?

NB: per il calcolo della matrice di Hankel utilizzare la function 

def Hankel(n):

    A=np.zeros((n,n),dtype=float)
    for i in range(0,n):
        for k in range(i+1-n,i+1):
            if k>0:
                A[i,n-1+k-i]=2.0**(k+1)
            else:
                A[i,n-1+k-i]=2.0**(1/(2-k-1))
    return A

## Esercizio 8

Ripetere l'esercizio precedente per risolvere il sistema lineare $Ax = b$
con $A$ e $b$ cos\`i  definiti:
$$
a^{(n)}_{i,j}=
\left \{
\begin{array}{ll}
1 & \hbox{se} \ i=j \ \hbox{o \, se} \ j=n,\\
-1 & \hbox{se} \ i>j,\\
0 & \hbox{altrimenti}
\end{array}
\right .
\qquad
b = A \cdot [1, ..., 1]^T,
$$
per $n = 48 : 2 : 58$ e $b$ scelto in modo che risulti $x = [1, 1, ..., 1]^T$. Che
cosa si osserva?