# Esercitazione 4 Marzo 2025

In [2]:
import numpy as np

## Esercizio 1
- Costruire due array numpy-array 2d di dimensione 5000x5000 i cui valori sono campionati da una distribuzione gaussiana con media 0 e varianza 1.
- Effetuare la somma tra le due matrici con due metodi:

        -  utilizzando le operazioni vettoriali 
        -  considerando due cicli espliciti annidati, su righe e colonne
- Confrontare le prestazioni in termini di tempo di esecuzione.
        


In [13]:
import time
arr1 = np.random.randn(5000, 5000)
arr2 = np.random.randn(5000, 5000)

start = time.time()
sumElementWise = arr1 + arr2
elapsed = time.time() - start

print(f"{sumElementWise}: {elapsed}ms")

start = time.time()
sumIterative = np.zeros_like(arr1)
for x in range(len(arr1)):
    for y in range(len(arr2)):
        sumIterative[x, y] = arr1[x, y] + arr2[x, y]
elapsed = time.time() - start

print(f"{sumIterative}: {elapsed}ms")

[[ 1.89480792e-01  1.98461355e+00  3.42387038e-01 ... -1.70858218e-01
   3.72094724e-03  1.40727307e+00]
 [-2.14436224e+00 -4.08362357e-01  1.52226673e+00 ... -4.44276429e-01
   1.22554736e+00 -1.54721922e+00]
 [ 7.52838951e-01  2.48339890e+00  5.26491464e-01 ...  1.39787539e+00
   1.61600415e-02  1.96941174e+00]
 ...
 [-1.61434388e+00  4.16478692e+00  1.64426268e+00 ...  9.32161701e-01
  -2.62811251e+00  1.85632596e+00]
 [ 8.68679359e-01  9.50432130e-01  6.48805838e-01 ... -1.84265609e+00
  -9.93025914e-01  2.23249476e-01]
 [-1.01442241e+00  2.40515016e-01  2.39074475e+00 ...  4.76726953e+00
   2.65821716e-01 -2.72698931e+00]]: 0.16747498512268066ms
[[ 1.89480792e-01  1.98461355e+00  3.42387038e-01 ... -1.70858218e-01
   3.72094724e-03  1.40727307e+00]
 [-2.14436224e+00 -4.08362357e-01  1.52226673e+00 ... -4.44276429e-01
   1.22554736e+00 -1.54721922e+00]
 [ 7.52838951e-01  2.48339890e+00  5.26491464e-01 ...  1.39787539e+00
   1.61600415e-02  1.96941174e+00]
 ...
 [-1.61434388e+00  4.

## Esercizio 2
-      Costruire il numpy array  s  formato da 40 valori equidistanti in  [0,20],
-      considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne e dire se il reshape crea una vista o una copia

In [ ]:
s = np.linspace(0, 20, 40)
s_matrix = s.reshape(4, 10)

# reshape() crea una copia!

array([[ 0.        ,  0.51282051,  1.02564103,  1.53846154,  2.05128205,
         2.56410256,  3.07692308,  3.58974359,  4.1025641 ,  4.61538462],
       [ 5.12820513,  5.64102564,  6.15384615,  6.66666667,  7.17948718,
         7.69230769,  8.20512821,  8.71794872,  9.23076923,  9.74358974],
       [10.25641026, 10.76923077, 11.28205128, 11.79487179, 12.30769231,
        12.82051282, 13.33333333, 13.84615385, 14.35897436, 14.87179487],
       [15.38461538, 15.8974359 , 16.41025641, 16.92307692, 17.43589744,
        17.94871795, 18.46153846, 18.97435897, 19.48717949, 20.        ]])

## Esercizio 3
-     Costruire il numpy array t formato da 100 valori equidistanti in  [0,4]
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [ ]:
t = np.linspace(0, 4, 100)
t_matrix = t.reshape(25, 4)

array([[0.        , 0.04040404, 0.08080808, 0.12121212],
       [0.16161616, 0.2020202 , 0.24242424, 0.28282828],
       [0.32323232, 0.36363636, 0.4040404 , 0.44444444],
       [0.48484848, 0.52525253, 0.56565657, 0.60606061],
       [0.64646465, 0.68686869, 0.72727273, 0.76767677],
       [0.80808081, 0.84848485, 0.88888889, 0.92929293],
       [0.96969697, 1.01010101, 1.05050505, 1.09090909],
       [1.13131313, 1.17171717, 1.21212121, 1.25252525],
       [1.29292929, 1.33333333, 1.37373737, 1.41414141],
       [1.45454545, 1.49494949, 1.53535354, 1.57575758],
       [1.61616162, 1.65656566, 1.6969697 , 1.73737374],
       [1.77777778, 1.81818182, 1.85858586, 1.8989899 ],
       [1.93939394, 1.97979798, 2.02020202, 2.06060606],
       [2.1010101 , 2.14141414, 2.18181818, 2.22222222],
       [2.26262626, 2.3030303 , 2.34343434, 2.38383838],
       [2.42424242, 2.46464646, 2.50505051, 2.54545455],
       [2.58585859, 2.62626263, 2.66666667, 2.70707071],
       [2.74747475, 2.78787879,

## Esercizio 4
Costruire il numpy array 1d C  di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente).  

In [17]:
C = np.arange(15, 41, 2)
print(C)

C.resize(7, 2)
print(C)

[15 17 19 21 23 25 27 29 31 33 35 37 39]
[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39  0]]


 ## Esercizio 5
 Creare un array NumPy di 10 numeri interi casuali tra 1 e 100.
 

In [20]:
rnd = np.random.randint(1, 100, 10)
print(rnd)

[36 73 99 57 31 59 54 79 41 16]


 ## Esercizio 6
 Eseguire uno shuffle degli elementi di un numpy-array di 30 numeri interi casuali tra 100 e 200.


In [21]:
aaaa = np.random.randint(100, 200, 30)
print(aaaa)

np.random.shuffle(aaaa)
print(aaaa)

[189 161 158 110 184 191 195 155 134 109 118 164 160 144 112 128 104 132
 128 100 186 197 156 178 198 136 100 156 163 173]
[197 160 198 134 110 144 136 158 128 104 186 191 178 156 164 100 161 109
 128 118 156 195 132 184 173 155 112 163 189 100]


  ## Esercizio 7
 Creare una permutazione casuale degli elementi di un numpy-array di 20 valori campionati da una distribuzione  gaussiana con media zero e varianza 1, senza modificarlo.

In [23]:
elements = np.random.randn(20)
print(elements)

permutation = np.random.permutation(elements)
print(permutation)

[ 1.38346124  0.13952182 -0.11220179  0.94887794 -2.02941803  0.07306592
 -0.98815428  0.64132457 -0.25369542  0.01707757 -0.0619629   0.35294322
 -1.06383552  1.03494968 -1.27673418 -0.88030159  0.87287542  0.16002195
 -1.45978469 -0.25634211]
[ 0.87287542  0.94887794  0.07306592 -1.27673418 -0.25369542 -0.11220179
 -0.0619629  -0.88030159  0.16002195  0.01707757 -2.02941803  1.38346124
  1.03494968 -0.98815428 -0.25634211 -1.45978469  0.64132457 -1.06383552
  0.13952182  0.35294322]


 ## Esercizio 8
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [ ]:
A = np.array([
    [10,11,12],
    [13,14,15],
    [16,17,18]
])
print(A)

# Crea una copia!
one_dimension = A.ravel()
print(one_dimension)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


## Esercizio 9
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [30]:
A = np.array([
    [10,11,12],
    [13,14,15],
    [16,17,18]
])
print(A)

print(A.flatten())

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[10 11 12 13 14 15 16 17 18]


 ## Esercizio 10
-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [35]:
f1 = np.array([ i for i in range(0, 16)])
f2 = np.array([ i for i in range(16, 32)])
print(f1)
print(f2)

f3 = f1.reshape(4, -1) @ f2.reshape(4, -1)
print(f3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


## Esercizio 11
Costruire:
 -     Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 "Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B


In [37]:
A = np.random.randn(2, 10)
B = np.array([ n for n in range(0, 20)])

sum = A.flatten() + B
print(sum)

[ 0.46727013  0.26541939  1.84843031  2.22319578  3.98649119  5.8123827
  6.94882401  9.17346815  7.42032304 10.05561766  9.94969444  9.95803098
 11.74591709 11.58307006 14.46564561 14.2111994  14.78842105 19.57135386
 17.95574085 19.60470472]


## Esercizio 12
-     Costruire f, un numpy array 1D , di shape (10,) costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [5]:
f = np.linspace(0, 1, 10)
f.resize((10, 1))
print(f)

[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


## Esercizio 13
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe

In [ ]:
a = np.array([14,13,12,11])
b = np.array([[4,3,2,1],
              [9,10,11,12]])
print(np.concatenate((a, b.flatten())))

array([14, 13, 12, 11,  4,  3,  2,  1,  9, 10, 11, 12])

## Esercizio 14
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

-
- Costruire il numpy array che si ottiene concatenando a e b per colonne

In [20]:
a = np.array([14,13,12,11])
b = np.array([[4,3,2,1],
              [9,10,11,12],
              [4,3,2,1],
              [9,10,11,12]])

print(np.concatenate((a.reshape((4,1)),b), axis=1))

[[14  4  3  2  1]
 [13  9 10 11 12]
 [12  4  3  2  1]
 [11  9 10 11 12]]


## Esercizio 15
Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale principale, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

In [ ]:
order = 10
A = 10 * np.eye(order * order)
print(A)

[[10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.

## Esercizio 16
Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

## Esercizio 17
Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?

## Esercizio 18
Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

## Esercizio 19

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A/B   dove  $\quad f_{ij}=a_{ij}/b_{ij} \quad i=0,..,n, \quad j=0,...,n$

## Esercizio 20
Dato array NumPy che rappresenta le vendite giornaliere di un negozio per un mese,
vendite = np.random.randint(50, 200, 30) 

        Trova tutti i giorni in cui le vendite sono state superiori a 150.

        Calcola la media delle vendite solo per i giorni in cui sono state superiori a 150.

        Imposta le vendite a 0 per tutti i giorni in cui sono state inferiori a 100.


## Esercizio 21
Costruisci A, un numpy array 2d di shape (3,3) e b,  un numpy array 2d di shape (3,1)
e somma b ad ogni colonna di A b


# Esercizio 22
dato il numpy array 2d G=np.linspace(0,10,20).reshape(-1,4), scambia in G la seconda riga con la quarta riga

## Esercizio 23
Visualizzare il grafico della funzione $f(x)=sin^2(x)/x$ in 200 punti equidistanti nell'intervallo $[0.1,2\pi]$

## Esercizio 24

Data il numpy arra2d ottenuto facendo un reshape a (4,4) di un numpy array 1d di 16 valori equidistanti nell'intervallo [0,4]
ed un numpy array 1d di 4 valori  interi casuali nell'intervallo [10,60], costruire il prodotto scalare A per b,
usando A@b, e vettorizzando solo il ciclo interno.


## Esercizio 25
Dato g un numpy array 2d, estendilo di una riga in alto ed di una riga in basso, di una colonna a sinistra ed di una colonna a destra, usa la funzione g_est= np.pad(g,(1,1),mode='reflect'). Visualizza 'g_est' e commenta cosa vedi.

## Esercizio 26
Scrivi un programma Python che esegua l'elaborazione di un'immagine utilizzando un filtro di media. 

Utilizza il padding per gestire i pixel del bordo durante l'applicazione del filtro.

Il programma deve seguire questi passaggi:

- Carica l'immagine: Carica l'immagine 'cameraman.png' utilizzando la libreria Matplotlib.**image=plt.imread('cameraman.png')**
- Visualizza l'immagine originale **plt.imshow(image,cmap='gray')**
- definisce la dimensione del filtro, dim_filtro
- Applica il padding: Applica un padding costante di dim_filtro//2 pixel a tutti i bordi dell'immagine (utilizzando il metodo di numpy **image_bordered=np.pad(image,(dim_filtro//2,dim_filtro//2),, mode='reflect')**
- Crea il filtro di media: Crea un filtro di media di dimensioni *dim_filtroxdim_filtro*, dove tutti gli elementi sono pari a 1/(dim_filtroxdim_filtro)
- Applica il filtro: Scorri ogni pixel dell'immagine con padding (escludendo i bordi aggiunti) e applica il filtro di media.

   *Per ogni pixel, calcola la somma dei prodotti tra i pixel della sottomatrice dim_filtroxdim_filtro centrata sul pixel corrente e il filtro.*
   
- Crea l'immagine filtrata: Crea un nuovo array NumPy che rappresenta l'immagine filtrata, dove ogni pixel contiene il risultato dell'applicazione del filtro.
- Visualizza l'immagine filtrata: Visualizza l'immagine filtrata utilizzando Matplotlib con la mappa di colori 'gray'.
- Aggiungi una colorbar per visualizzare la scala dei valori dell'immagine filtrata.
- Mostra l'immagine filtrata con Matplotlib.


Requisiti:

-  Utilizzare la libreria Matplotlib per caricare e visualizzare l'immagine.
-  Utilizzare la libreria NumPy per la manipolazione degli array e per il padding.